#ifndef _PERIPHERAL_H
#define _PERIPHERAL_H

#define ROM_BASE 0x00000000UL
#define LLRAM_BASE 0x00080000UL
#define CHIPSET_BASE 0x00100000UL
#define SDRAM_BASE 0x80000000UL

#define PERIPHERAL_INTERRUPT_BASE (CHIPSET_BASE + 0x000)
#define PERIPHERAL_TIMER_BASE (CHIPSET_BASE + 0x200)
#define PERIPHERAL_SPI_BASE (CHIPSET_BASE + 0x800)
#define PERIPHERAL_UART_BASE (CHIPSET_BASE + 0x900)
#define PERIPHERAL_VGA_BASE (CHIPSET_BASE + 0xA00)
#define PERIPHERAL_SOUND_BASE (CHIPSET_BASE + 0xB00)

typedef enum PeripheralID PeripheralID;
enum PeripheralID {
	PERIPHERAL_ID_TIMER = 2,
	PERIPHERAL_ID_SPI = 8,
	PERIPHERAL_ID_UART,
	PERIPHERAL_ID_VGA,
	PERIPHERAL_ID_AUDIO,
	PERIPHERAL_ID_EXTINT1 = 15,
	PERIPHERAL_ID_EXTINT2,
	PERIPHERAL_ID_EXTINT3,
	PERIPHERAL_ID_EXTINT4,
};

#endif
